### ISSUE TITLE
Why is `default_host` mandatory?

### ISSUE THREAD

**Issue by yoshigev** [googleapis/gapic-config-validator#236]
Reading [AIP 4210](https://google.aip.dev/client-libraries/4210), it states that:

> If the `google.api.default_host` annotation is not present on the service directive, then the generated class should require a hostname when it is instantiated.

According to this, there is a possibility of `default_host` to be empty.

So, why is it mandated on the validator (and hence all gapic client libraries generators)?

Is there a way to make the validator skip this validation or give a default value from outside?

Thanks,
Yehoshua

**Comment by noahdietz** [comment]
It is actually required for the Go GAPIC generator. It was "required" for backward compatibility reasons. 

> Is there a way to make the validator skip this validation?

No, but perhaps there should be!

**Comment by yoshigev** [comment]
Thanks for the reply.

From my perspective, stricness of validation is quite the opposite of _backward_ compatibility, as adding adding validations can break existing usages while removing validations usually don't break anything (apart from regression tests). Stict validation is required for _forward_ compatibility.

I know that my voice will probably not have significant effect, but I think that if you'll decide to add a flag for controlling this validation, the default should be to skip validation. So only the Go generator will set the flag to perform this validation.

As I got my reply, I'm closing the issue. Thanks again.
